db-uri = "postgresql://authenticator:postgrest_password@localhost:5432/webstudio"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "super-secret-jwt-token-with-at-least-32-characters-long"
server-port = 3000
