db-uri = "postgresql://postgres:sahil%231010@localhost:5432/webstudio"
db-schemas = "public"
db-anon-role = "anon"
db-use-legacy-gucs = false
jwt-secret = "jwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecret"
server-port = 3000
